# Numpy

Numpy Arrays

In [1]:
my_list = [1, 2, 3] # reuglar python list

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list) # turning the list into a numpy array

array([1, 2, 3])

In [5]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # 2D np array

In [6]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.arange(start, stop, step)

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(1,4,1)

array([1, 2, 3])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.linspace(start, stop, num)

In [27]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

NOTE: 

The difference between np.arange() and np.linspace() is the 3rd parameter. For np.arange(), it is "step". Think of skip counting. The "step" is the number that you are skip counting by starting form the start value until (not including) the stop value. 

np.linspace() has the third parameter as the number of evenly-spaced values in between the start and the stop value, including both.

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.random.rand(5,5)

array([[0.51916172, 0.94486696, 0.00364422, 0.54858218, 0.93479051],
       [0.16696769, 0.92551965, 0.66071896, 0.11281472, 0.76095775],
       [0.70678829, 0.01456446, 0.34879645, 0.45345279, 0.97883868],
       [0.86658694, 0.35187867, 0.8484185 , 0.66860385, 0.89075118],
       [0.14930551, 0.28693715, 0.99735325, 0.68421317, 0.84272386]])

In [68]:
arr = np.random.randint(1,100,10)

In [70]:
arr = arr.reshape(5, 2)

In [72]:
arr.max()

95

In [73]:
arr.min()

3

In [74]:
arr.argmax()

9

In [75]:
arr.argmin()

1

In [76]:
arr.dtype

dtype('int32')

In [77]:
arr.shape

(5, 2)

In [78]:
arr

array([[76,  3],
       [81, 47],
       [ 5, 39],
       [11, 77],
       [84, 95]])

# Pandas 

- Series
- DataFrames
- Missing Data
- Merging, Joining, and Concatenating
- Operations
- Data input and output

In [79]:
import pandas as pd

In [81]:
labels = ["x", "y", "z"]
my_data = [3, 4, 5]

In [98]:
array = np.array(my_data)

In [99]:
pd.Series(data = array, index= labels)

x    3
y    4
z    5
dtype: int32

In [91]:
df = pd.DataFrame(np.random.rand(5, 4), ['A', 'B', 'C', 'D', "E"])

In [92]:
df

0         1         2         3
A  0.255285  0.787884  0.218329  0.482651
B  0.643252  0.525144  0.421084  0.916959
C  0.292914  0.084000  0.688457  0.713667
D  0.550077  0.973644  0.286880  0.440177
E  0.136670  0.771534  0.338179  0.560748

In [106]:
df['new'] = df[0] + df[1]

In [107]:
df

0         1         2         3       new
A  0.255285  0.787884  0.218329  0.482651  1.043169
B  0.643252  0.525144  0.421084  0.916959  1.168397
C  0.292914  0.084000  0.688457  0.713667  0.376914
D  0.550077  0.973644  0.286880  0.440177  1.523721
E  0.136670  0.771534  0.338179  0.560748  0.908204

In [115]:
df.drop("new", axis=1)

0         1         2         3
A  0.255285  0.787884  0.218329  0.482651
B  0.643252  0.525144  0.421084  0.916959
C  0.292914  0.084000  0.688457  0.713667
D  0.550077  0.973644  0.286880  0.440177
E  0.136670  0.771534  0.338179  0.560748

In [109]:
df.loc['A']

0      0.255285
1      0.787884
2      0.218329
3      0.482651
new    1.043169
Name: A, dtype: float64

In [112]:
df.loc["B", 3]

0.9169589239617214

In [116]:
df

0         1         2         3       new
A  0.255285  0.787884  0.218329  0.482651  1.043169
B  0.643252  0.525144  0.421084  0.916959  1.168397
C  0.292914  0.084000  0.688457  0.713667  0.376914
D  0.550077  0.973644  0.286880  0.440177  1.523721
E  0.136670  0.771534  0.338179  0.560748  0.908204

In [118]:
df.dropna() # there are no null values so nothing changed. This method removes all rows with null values.

0         1         2         3       new
A  0.255285  0.787884  0.218329  0.482651  1.043169
B  0.643252  0.525144  0.421084  0.916959  1.168397
C  0.292914  0.084000  0.688457  0.713667  0.376914
D  0.550077  0.973644  0.286880  0.440177  1.523721
E  0.136670  0.771534  0.338179  0.560748  0.908204

In [119]:
df.fillna(1) # there are no null values so nothing changed. This method will replace null values with the passed parameter.

0         1         2         3       new
A  0.255285  0.787884  0.218329  0.482651  1.043169
B  0.643252  0.525144  0.421084  0.916959  1.168397
C  0.292914  0.084000  0.688457  0.713667  0.376914
D  0.550077  0.973644  0.286880  0.440177  1.523721
E  0.136670  0.771534  0.338179  0.560748  0.908204

In [122]:
Snow = pd.read_csv("SnowDayData.csv") # IMPORTANT: remember to use tab to auto-complete!

In [125]:
Snow.head(3)

Date  Maximum  Minimum  Average  Departure  HDD  CDD  Percipitation  \
0  2023-01-01       49       41     45.0       14.0   20    0           0.28   
1  2023-01-02       51       34     42.5       11.7   22    0           0.00   
2  2023-01-03       53       35     44.0       13.4   21    0           0.03   

   New Snow  Snow Depth  Snow Day  
0       0.0         0.0         0  
1       0.0         0.0         0  
2       0.0         0.0         0

In [128]:
Snow["Date"].unique() # returns numpy array of all unique values in pandas Series

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31', '2022-01-01',
       '2022-01-02', '2022-01-03', '2022-01-04', '2022-01-05',
       '2022-01-06', '2022-01-07', '2022-01-08', '2022-01-09',
       '2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13',
       '2022-01-14', '2022-01-15', '2022-01-16', '2022-01-17',
       '2022-01-18', '2022-01-19', '2022-01-20', '2022-01-21',
       '2022-01-22', '2022-01-23', '2022-01-24', '2022-01-25',
       '2022-01-26', '2022-01-27', '2022-01-28', '2022-01-29',
       '2022-01-30', '2022-01-31', '2022-12-01', '2022-

In [129]:
Snow["Date"].nunique() # returns number of unique values in pandas Series

93

In [131]:
Snow["Snow Depth"].value_counts() # the number of times each unique value appears in the column

0.0    84
1.0     3
4.0     2
0.1     1
0.3     1
0.8     1
2.0     1
Name: Snow Depth, dtype: int64